### ISSUE TITLE
请问能提供一个混淆的配置吗？

### ISSUE THREAD

**Issue by sean-looong** [yuanhoujun/Android_Slide_To_Close#10]

**Comment by yuanhoujun** [comment]
好的建议，下个版本提供混淆配置, 目前可以暂时全部混淆

**Comment by sean-looong** [comment]
谢谢，是个好库。

**Comment by jhyc** [comment]
今天偶然发现这个库，试用了下很方便啊。赞一个

**Comment by yuanhoujun** [comment]
谢谢你的肯定，💪 别忘了推荐给朋友哦

**Comment by yuanhoujun** [comment]
已更新至0.3.2，新版本文档中增加了混淆配置说明，请参考文档进行配置。

**Comment by sean-looong** [comment]
谢谢 O(∩_∩)O

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: 欧阳锋 <notifications@github.com>
发送时间: Wednesday, July 11, 2018 3:41:48 PM
收件人: yuanhoujun/Snake
抄送: sean-looong; Author
主题: Re: [yuanhoujun/Snake] 请问能提供一个混淆的配置吗？ (#10)


已更新至0.3.2，新版本文档中增加了混淆配置说明，请参考文档进行配置。

―
