### ISSUE TITLE
滑动事件如何监听

### ISSUE THREAD

**Issue by sean-looong** [yuanhoujun/Android_Slide_To_Close#12]
您好，因为现在使用snake之后，滑动返回上一个页面fragment没有生命周期的回调，导致我没办法在onResume的时候刷新界面。请问如何使用dragListener监听滑动事件。

**Comment by sean-looong** [comment]
知道怎么用了。谢谢。
Snake.addDragListener(this, new Snake.OnDragListener() {......}

**Comment by yuanhoujun** [comment]
Ok，问题先关闭了哈。
