### ISSUE TITLE
Could not find com.youngfeng.android:snake-compiler:0.3.2.

### ISSUE THREAD

**Issue by guobosheng** [yuanhoujun/Android_Slide_To_Close#17]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:kaptGenerateStubsHangarDebugKotlin'.
> Could not resolve all files for configuration ':app:kapt'.
   > Could not find com.youngfeng.android:snake-compiler:0.3.2.
     Searched in the following locations:
         file:/C:/Users/Administrator/AppData/Local/Android/Sdk/extras/m2repository/com/youngfeng/android/snake-compiler/0.3.2/snake-compiler-0.3.2.pom
         file:/C:/Users/Administrator/AppData/Local/Android/Sdk/extras/m2repository/com/youngfeng/android/snake-compiler/0.3.2/snake-compiler-0.3.2.jar
         file:/C:/Users/Administrator/AppData/Local/Android/Sdk/extras/google/m2repository/com/youngfeng/android/snake-compiler/0.3.2/snake-compiler-0.3.2.pom
         file:/C:/Users/Administrator/AppData/Local/Android/Sdk/extras/google/m2repository/com/youngfeng/android/snake-compiler/0.3.2/snake-compiler-0.3.2.jar
         file:/C:/Users/Administrator/AppData/Local/Android/Sdk/extras/android/m2repository/com/youngfeng/android/snake-compiler/0.3.2/snake-compiler-0.3.2.pom
         file:/C:/Users/Administrator/AppData/Local/Android/Sdk/extras/android/m2repository/com/youngfeng/android/snake-compiler/0.3.2/snake-compiler-0.3.2.jar
         https://dl.google.com/dl/android/maven2/com/youngfeng/android/snake-compiler/0.3.2/snake-compiler-0.3.2.pom
         https://dl.google.com/dl/android/maven2/com/youngfeng/android/snake-compiler/0.3.2/snake-compiler-0.3.2.jar
         http://maven.aliyun.com/nexus/content/groups/public/com/youngfeng/android/snake-compiler/0.3.2/snake-compiler-0.3.2.pom
         http://maven.aliyun.com/nexus/content/groups/public/com/youngfeng/android/snake-compiler/0.3.2/snake-compiler-0.3.2.jar
         https://jcenter.bintray.com/com/youngfeng/android/snake-compiler/0.3.2/snake-compiler-0.3.2.pom
         https://jcenter.bintray.com/com/youngfeng/android/snake-compiler/0.3.2/snake-compiler-0.3.2.jar
         https://jitpack.io/com/youngfeng/android/snake-compiler/0.3.2/snake-compiler-0.3.2.pom
         https://jitpack.io/com/youngfeng/android/snake-compiler/0.3.2/snake-compiler-0.3.2.jar
     Required by:
         project :app

**Comment by yuanhoujun** [comment]
snake-compiler的最新版本是0.3.0
