### ISSUE TITLE
请修复内存泄漏问题，谢谢。

### ISSUE THREAD

**Issue by silica-github** [yuanhoujun/Android_Slide_To_Close#3]

**Comment by yuanhoujun** [comment]
可否详细描述一下你的问题？

**Comment by yuki-ryoko** [comment]
感谢秒回复。
在所有 Activity 都继承 BaseActivity 的情况下，允许滑动返回的 Activity 通过右滑或者返回键 finish() ，Android Studio 和 Leaks 都会报内存泄漏；关闭滑动返回的 Activity 则不会出现这种情况。目前在我正在进行的公司正式项目上，每一次的 finish() 都会有大约 2MB 的内存泄漏。
压缩包里含有 AS 和 Leaks 的截图与 Dump文件，烦请查看，谢谢您的付出。

**Comment by silica-github** [comment]
感谢秒回复，公司上行有点问题，附件上传费了点时间。
在所有 Activity 都继承 BaseActivity 的情况下，允许滑动返回的 Activity 通过右滑或者返回键 finish() ，Android Studio 和 Leaks 都会报内存泄漏；关闭滑动返回的 Activity 则不会出现这种情况。目前在我正在进行的公司正式项目上，每一次的 finish() 都会有大约 2MB 的内存泄漏。
压缩包里含有 AS 和 Leaks 的截图与 Dump文件，烦请查看，谢谢您的付出。
附件：https://github.com/yuki-ryoko/Hungry/blob/master/Snake.zip

**Comment by yuanhoujun** [comment]
OK, 我会尽快修复这个问题

**Comment by yuanhoujun** [comment]
问题已修复，版本升级到0.0.6问题就会引刃而解!
