### ISSUE TITLE
页面滑动关闭的监听

### ISSUE THREAD

**Issue by gaojunhuiBS** [yuanhoujun/Android_Slide_To_Close#7]
您好，如何监听页面是通过滑动关闭了，比如我想setResult,是否能提供一个滑动关闭的监听。

**Comment by yuanhoujun** [comment]
如果打开新页面是用于获取数据回调处理，可以使用注解@EnableDragToClose(false)关闭当前页面滑动关闭功能，这样其实更好。

**Comment by yuanhoujun** [comment]
如果一定要使用滑动关闭完成数据回调的话，可以在获取数据页面重写finish方法，在super.finish之前完成setResult

**Comment by gaojunhuiBS** [comment]
谢谢

**Comment by yuanhoujun** [comment]
😜 欢迎继续提问题哦。

**Comment by gaojunhuiBS** [comment]
如果，可能，还是建议添加一个能滑动关闭的监听，因为在finishi里面setResult,还需要做一些其他操作结束页面的判断，我认为有这个监听，会全面很多。
